import type { Key } from "lmdb";
import { getAggregateDatabase, readAggregateRecord } from "./database";
import type { AggregateOptions } from "./types";

/**
 * The stored value, in O(1) — one key read, no corpus load.
 *
 * `null` means "never computed": an unbuilt aggregate, or a fixture captured
 * before this aggregate was declared. Deliberately distinct from an empty
 * value, since "no tags yet" and "nobody has folded the tags" are different
 * states and only one of them is worth repairing. Callers that just want to
 * render write `?? []`.
 *
 * A read never triggers the pass. That is the same rule pagination reads
 * follow, and for the same reason: a read may be inside a static export or on
 * a read-only mount. It is also why every Playwright fixture has to be
 * regenerated by script rather than left to heal itself (§13).
 *
 * @example
 * ```ts
 * const tags = (await readAggregate({
 *   config: noteConfig,
 *   aggregateConfig: noteTags,
 * })) ?? [];
 * ```
 */
export async function readAggregate<
  TIndexValue,
  TKey extends Key,
  TAccumulator,
  TValue,
>(
  options: AggregateOptions<TIndexValue, TKey, TAccumulator, TValue>,
): Promise<TValue | null> {
  const { config, aggregateConfig, contentDirectory } = options;
  const db = getAggregateDatabase(config, aggregateConfig, contentDirectory);
  const record = readAggregateRecord<TValue>(db);
  return record ? record.value : null;
}

export default readAggregate;
