import type { PaginationIndexConfig } from "@discontent/cms/pagination/types";
import type { ProjectEntryKey, ProjectEntryValue } from "./types";

/**
 * How many projects a numbered index page carries.
 *
 * Declared here rather than read from a component constant — which is where
 * recipe keeps its equivalent (`RecipeIndexPage/constants.ts`) — because
 * portfolio has no index-page component to keep it next to. The homepage
 * renders the whole corpus and always has; see `readIndex.ts`.
 */
export const PROJECTS_PER_PAGE = 12;

/**
 * What one row of a paginated project index carries.
 *
 * Deliberately near-identity — `{ slug, date, ...ProjectEntryValue }` — where
 * recipe's equivalent is deliberately narrow. That is not an oversight, and the
 * rule recipe's `RecipeListEntry` states ("a field carried here that nobody
 * renders dirties sealed pages every time it changed") is not being ignored so
 * much as coming out the other way here: portfolio's three index postures
 * collectively render `name`, `summary`, `tags`, `image`, `featured`, `role`
 * and `date`, and client-side search matches `client` on top of that. That is
 * every field on `ProjectEntryValue`. There is no narrower honest projection,
 * and guessing one would only be a projection a future index route has to bump
 * the version to widen again.
 *
 * Structurally the same declaration as `data/readIndex.ts`'s
 * `ProjectIndexEntry`, and redeclared rather than imported on purpose: this
 * module is imported *by* `projectContentConfig`, so it may import only types
 * that do not lead back to it. `./types` does not; `./data/readIndex` does.
 */
export interface ProjectListEntry extends ProjectEntryValue {
  slug: string;
  date: number;
}

/**
 * Projects by date, newest first.
 *
 * Its own module rather than a field inside `projectContentConfig.ts`: the
 * content config imports this, and this imports only *types* back, so there is
 * no cycle. It belongs to the collection package rather than to portfolio for
 * the same reason — the config that has to import it lives here, and a package
 * reaching into a site that consumes it inverts the dependency.
 */
export const projectsByDate: PaginationIndexConfig<
  ProjectEntryValue,
  ProjectEntryKey,
  ProjectListEntry
> = {
  name: "by-date",
  perPage: PROJECTS_PER_PAGE,
  /*
   * The whole of this index's spec hash — declared, not derived.
   *
   * The engine once folded `fn.toString()` in too, which a production build
   * minifies and a dev server does not, so an index built by one and read by
   * the other read as stale and rebuilt itself — every page dirty, every time.
   * Portfolio crosses that boundary on every gated run: the Playwright
   * fixtures are generated by a script and the suite runs against a build, and
   * a real deployment crosses it whenever the editor and the export build
   * share a content directory. F16 removed the derived half.
   *
   * So bump this by hand when `key` or `project` changes — nothing else will
   * notice. `test/specVersions.test.ts` fails on any edit to this file until
   * someone has decided whether it needed a bump.
   */
  version: "1",
  /*
   * The date lives in the content index *key*, not the value — `buildIndexKey`
   * is `[date, slug]` while `ProjectEntryValue` carries no date at all. Both
   * functions below therefore read it from `entry.key`, exactly as recipe's do.
   */
  key: ({ key: [date], id }) => [date, id],
  project: ({ key: [date], value, id }) => ({
    ...value,
    slug: id,
    date,
  }),
};

export default projectsByDate;
